### ISSUE TITLE
customjsonを導入後にinfo.txtに多数のエラーが生成されます

### ISSUE THREAD

**Issue by Xcreezaz430** [po-po-po-pong/umaumacruise_customjson#4]
customjsonを導入後にinfo.txtに多数のエラーが生成されます
[error]: 選択肢の数が kMaxOption を超えます: With
[error]: 選択肢の数が kMaxOption を超えます: あんし〜ん笹針師、参☆上
[error]: 選択肢の数が kMaxOption を超えます: 福引チャンス！
がほとんどを占めますが一部レース後のイベントでも吐いているようです
テイエムオペラオー(及び別衣装)：有馬記念の後に
ネオユニヴァース：皐月賞の後に
アグネスデジタル(及び別衣装)：マイルCSの後に

kMaxOptionは推定4のようでそれを超えるイベントでエラーを返しています

**Comment by po-po-po-pong** [comment]
ご連絡ありがとうございます。
選択肢数を最大4で出力するように変更致しました。
当方環境の info.log に該当のエラーが記録されない事を確認しております。

2024/04/21版より適用しておりますので、お手数ですがご確認ください。
